"use client";

import { useMemo, useState } from "react";
import Link from "next/link";
import {
  SHARE_CHANNELS,
  SHARE_TARGETS,
  SITE_ORIGIN,
  buildShareUrl,
  normalizeTag,
  qrImageUrl,
  type ShareChannel,
} from "@/lib/share-links";

/**
 * Sharing panel for `/admin/share`: one ready-to-copy link per channel, each
 * with its QR code, plus how many visits that channel has actually brought.
 */

export interface VisitsByTag {
  /** Visits per `?src=` tag since the beginning. */
  totals: Record<string, number>;
  /** Visits per tag in the last 30 days. */
  recent: Record<string, number>;
}

const CARD =
  "rounded-2xl bg-white p-5 shadow-sm ring-1 ring-black/5 dark:bg-white/[0.06] dark:ring-white/10";

function VisitBadge({ visits, tag }: { visits: VisitsByTag; tag: string }) {
  const total = visits.totals[tag] ?? 0;
  const recent = visits.recent[tag] ?? 0;
  if (total === 0) {
    return (
      <span className="whitespace-nowrap text-xs text-neutral-400">
        Sin visitas todavía
      </span>
    );
  }
  return (
    <span className="whitespace-nowrap text-xs text-neutral-500 dark:text-neutral-400">
      <strong className="font-semibold text-[#2a78d6] dark:text-[#3987e5]">
        {recent}
      </strong>{" "}
      en 30 días · {total} en total
    </span>
  );
}

function LinkRow({
  channel,
  url,
  visits,
}: {
  channel: ShareChannel;
  url: string;
  visits: VisitsByTag;
}) {
  const [copied, setCopied] = useState(false);

  const copy = async () => {
    try {
      await navigator.clipboard.writeText(url);
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    } catch {
      // Clipboard blocked: the field below is selectable, so copying by hand works.
    }
  };

  return (
    <div className={`${CARD} flex flex-col gap-4 sm:flex-row sm:items-start`}>
      <div className="min-w-0 flex-1">
        <div className="flex flex-wrap items-baseline justify-between gap-x-3 gap-y-1">
          <h3 className="text-sm font-semibold">
            <span aria-hidden>{channel.emoji}</span> {channel.label}
          </h3>
          <VisitBadge visits={visits} tag={channel.tag} />
        </div>
        <p className="mt-0.5 text-xs text-neutral-500 dark:text-neutral-400">
          {channel.hint}
        </p>

        <div className="mt-3 flex flex-wrap items-center gap-2">
          <input
            readOnly
            value={url}
            onFocus={(event) => event.currentTarget.select()}
            aria-label={`Enlace para ${channel.label}`}
            className="min-w-0 flex-1 rounded-full bg-black/5 px-3.5 py-2 font-mono text-xs text-neutral-700 outline-none dark:bg-white/10 dark:text-neutral-200"
          />
          <button
            type="button"
            onClick={copy}
            className={`rounded-full px-4 py-2 text-xs font-semibold transition ${
              copied
                ? "bg-emerald-500/15 text-emerald-600 dark:text-emerald-400"
                : "bg-black text-white hover:scale-[1.03] dark:bg-white dark:text-black"
            }`}
          >
            {copied ? "Copiado ✓" : "Copiar"}
          </button>
        </div>
      </div>

      <div className="flex items-center gap-3 sm:flex-col sm:gap-1.5">
        {/* eslint-disable-next-line @next/next/no-img-element -- generated by /api/qr */}
        <img
          src={qrImageUrl(url)}
          alt={`Código QR del enlace para ${channel.label}`}
          width={84}
          height={84}
          className="size-[84px] shrink-0 rounded-xl bg-white p-1.5 ring-1 ring-black/10"
        />
        <p className="text-[11px] text-neutral-400">
          <a
            href={qrImageUrl(url, { format: "png", size: 1024 })}
            download={`qr-${channel.tag}.png`}
            className="font-semibold text-neutral-500 underline underline-offset-2 dark:text-neutral-300"
          >
            PNG
          </a>{" "}
          ·{" "}
          <a
            href={qrImageUrl(url)}
            download={`qr-${channel.tag}.svg`}
            className="font-semibold text-neutral-500 underline underline-offset-2 dark:text-neutral-300"
          >
            SVG
          </a>
        </p>
      </div>
    </div>
  );
}

export default function ShareLinks({
  visits,
  email,
}: {
  visits: VisitsByTag;
  email: string;
}) {
  const [path, setPath] = useState(SHARE_TARGETS[0].path);
  const [customTag, setCustomTag] = useState("");

  const customChannel: ShareChannel | null = useMemo(() => {
    const tag = normalizeTag(customTag);
    if (!tag) return null;
    return {
      tag,
      label: `Etiqueta propia · ${tag}`,
      hint: "Úsala para una persona o empresa concreta y sabrás si abrió el enlace.",
      emoji: "🏷️",
    };
  }, [customTag]);

  return (
    <div className="min-h-screen bg-[#f5f5f7] text-[#1d1d1f] dark:bg-[#050505] dark:text-white">
      <header className="sticky top-0 z-40 border-b border-black/5 bg-white/85 backdrop-blur-xl dark:border-white/10 dark:bg-black/70">
        <div className="mx-auto flex max-w-4xl flex-wrap items-center justify-between gap-3 px-4 py-3">
          <div className="min-w-0">
            <h1 className="truncate text-sm font-semibold">Compartir mi web</h1>
            <p className="truncate text-xs text-neutral-400">{email}</p>
          </div>
          <div className="flex flex-wrap items-center gap-2">
            <Link
              href="/admin/stats"
              className="rounded-full border border-black/10 px-3 py-1.5 text-xs font-semibold dark:border-white/15"
            >
              Métricas
            </Link>
            <Link
              href="/admin"
              className="rounded-full bg-black px-4 py-1.5 text-xs font-semibold text-white transition hover:scale-[1.03] dark:bg-white dark:text-black"
            >
              ← Volver al editor
            </Link>
          </div>
        </div>
      </header>

      <main className="mx-auto max-w-4xl space-y-4 px-4 py-6">
        <section className={CARD}>
          <h2 className="text-sm font-semibold">Qué enlace quieres compartir</h2>
          <p className="mt-0.5 text-xs text-neutral-500 dark:text-neutral-400">
            Elige el destino y copia abajo la versión de cada canal. Cada enlace
            lleva su etiqueta, así sabrás por dónde llegó cada persona — y si
            terminó descargando el CV.
          </p>
          <div className="mt-3 flex flex-wrap gap-1.5">
            {SHARE_TARGETS.map((target) => (
              <button
                key={target.path}
                type="button"
                onClick={() => setPath(target.path)}
                title={target.hint}
                className={`rounded-full px-4 py-1.5 text-sm font-medium transition ${
                  path === target.path
                    ? "bg-black text-white dark:bg-white dark:text-black"
                    : "text-neutral-500 hover:bg-black/5 dark:hover:bg-white/10"
                }`}
              >
                {target.label}
              </button>
            ))}
          </div>
        </section>

        {SHARE_CHANNELS.map((channel) => (
          <LinkRow
            key={channel.tag}
            channel={channel}
            url={buildShareUrl(SITE_ORIGIN, path, channel.tag)}
            visits={visits}
          />
        ))}

        <section className={CARD}>
          <h2 className="text-sm font-semibold">🏷️ Etiqueta propia</h2>
          <p className="mt-0.5 text-xs text-neutral-500 dark:text-neutral-400">
            Para un destinatario concreto: <code>santander</code>,{" "}
            <code>feria-empleo</code>, <code>profesor-mendez</code>. Solo
            minúsculas, números y guiones.
          </p>
          <input
            value={customTag}
            onChange={(event) => setCustomTag(event.target.value)}
            placeholder="santander"
            aria-label="Etiqueta propia"
            className="mt-3 w-full max-w-xs rounded-full bg-black/5 px-3.5 py-2 text-sm outline-none ring-1 ring-transparent focus:ring-black/15 dark:bg-white/10 dark:focus:ring-white/20"
          />
        </section>

        {customChannel && (
          <LinkRow
            channel={customChannel}
            url={buildShareUrl(SITE_ORIGIN, path, customChannel.tag)}
            visits={visits}
          />
        )}

        <section className={CARD}>
          <h2 className="text-sm font-semibold">Cómo leerlo después</h2>
          <ul className="mt-2 space-y-1.5 text-sm leading-relaxed text-neutral-600 dark:text-neutral-300">
            <li>
              • Cada etiqueta aparece en{" "}
              <Link href="/admin/stats" className="underline underline-offset-2">
                Métricas → Origen de las visitas
              </Link>
              .
            </li>
            <li>
              • <strong>reshare</strong> se aplica solo: es lo que reparte el
              botón «Compartir» del sitio, así que mide el boca a boca.
            </li>
            <li>
              • Si compartes un enlace sin etiqueta, la visita se cuenta igual:
              aparecerá como el sitio de origen (LinkedIn, Google…) o como
              «Directo».
            </li>
            <li>
              • Los QR codifican el enlace con su etiqueta ya incluida. El SVG es
              vectorial: úsalo para imprimir a cualquier tamaño.
            </li>
          </ul>
        </section>
      </main>
    </div>
  );
}
