import type { SignerError } from "@/app/sign/actions";
import type { DocLang } from "@/lib/signed-docs";

/** The words on a signer's page, in the language the document was sent in. */
export const SIGN_COPY = {
  es: {
    pageTitle: "Firmar documento",
    sentBy: (owner: string) => `${owner} te envió este documento para firmar.`,
    hello: (name: string) => `Hola, ${name}`,
    pages: (n: number) => `${n} ${n === 1 ? "página" : "páginas"}`,
    verifyTitle: "Confirma que eres tú",
    verifyBody: (email: string) =>
      `Te enviaremos un código de 6 dígitos a ${email}. Con él podrás ver el documento y firmarlo.`,
    sendCode: "Enviar código",
    sending: "Enviando…",
    codeSent: (email: string) => `Enviamos un código a ${email}. Revisa también el spam.`,
    codeLabel: "Código",
    verify: "Confirmar",
    verifying: "Confirmando…",
    resend: "Enviar otro código",
    reviewTitle: "Revisa el documento",
    reviewBody: "Los recuadros marcan dónde irá tu firma.",
    yourSignatureHere: "Tu firma",
    download: "Descargar original",
    signTitle: "Tu firma",
    draw: "Dibujar",
    type: "Escribir",
    drawHint: "Firma con el dedo o el mouse dentro del recuadro.",
    clear: "Borrar",
    typeLabel: "Tu nombre",
    consent:
      "Acepto firmar electrónicamente este documento y que esta firma tenga la misma validez que mi firma manuscrita.",
    sign: "Firmar",
    signing: "Firmando…",
    decline: "Rechazar",
    declineTitle: "¿Por qué no firmas?",
    declinePlaceholder: "Cuéntale el motivo a quien te lo envió",
    declineConfirm: "Rechazar firma",
    cancel: "Cancelar",
    signedTitle: "¡Listo, firmaste!",
    signedBody:
      "Cuando firmen todos, recibirás por correo el PDF firmado y su certificado de auditoría.",
    completedBody: "Eras la última firma: el documento está completo. Te enviamos el PDF firmado por correo.",
    viewVerification: "Ver verificación",
    declinedTitle: "Rechazaste firmar",
    declinedBody: "Avisamos a quien te lo envió.",
    invalidTitle: "Este enlace no es válido",
    invalidBody:
      "Puede que esté incompleto o que te hayan enviado uno nuevo. Usa el enlace del correo más reciente.",
    closed: {
      completed: "Este documento ya fue firmado por todos.",
      declined: "Este documento fue rechazado y ya no se puede firmar.",
      cancelled: "Quien envió este documento canceló la solicitud.",
      expired: "El plazo para firmar este documento venció.",
      done: "Ya respondiste a esta solicitud. Gracias.",
    },
    errors: {
      link: "Este enlace ya no es válido.",
      closed: "Este documento ya no se puede firmar.",
      unverified: "Tu verificación venció. Vuelve a confirmar tu correo.",
      wait: "Espera un minuto antes de pedir otro código.",
      limit: "Pediste demasiados códigos hoy. Inténtalo mañana.",
      email: "No pudimos enviar el correo. Inténtalo de nuevo en unos minutos.",
      wrong: "Ese código no es correcto.",
      expired: "El código venció. Pide uno nuevo.",
      locked: "Demasiados intentos. Pide un código nuevo.",
      image: "Dibuja o escribe tu firma primero.",
      consent: "Marca la casilla para aceptar la firma electrónica.",
      reason: "Escribe el motivo.",
      server: "Algo falló de nuestro lado. Inténtalo de nuevo.",
    } satisfies Record<SignerError, string>,
    loadError: "No pude mostrar el documento. Descárgalo para revisarlo.",
  },
  en: {
    pageTitle: "Sign document",
    sentBy: (owner: string) => `${owner} sent you this document to sign.`,
    hello: (name: string) => `Hi, ${name}`,
    pages: (n: number) => `${n} ${n === 1 ? "page" : "pages"}`,
    verifyTitle: "Confirm it's you",
    verifyBody: (email: string) =>
      `We'll send a 6-digit code to ${email}. With it you can view the document and sign it.`,
    sendCode: "Send code",
    sending: "Sending…",
    codeSent: (email: string) => `We sent a code to ${email}. Check your spam folder too.`,
    codeLabel: "Code",
    verify: "Confirm",
    verifying: "Confirming…",
    resend: "Send another code",
    reviewTitle: "Review the document",
    reviewBody: "The boxes show where your signature will go.",
    yourSignatureHere: "Your signature",
    download: "Download original",
    signTitle: "Your signature",
    draw: "Draw",
    type: "Type",
    drawHint: "Sign with your finger or mouse inside the box.",
    clear: "Clear",
    typeLabel: "Your name",
    consent:
      "I agree to sign this document electronically and that this signature has the same validity as my handwritten one.",
    sign: "Sign",
    signing: "Signing…",
    decline: "Decline",
    declineTitle: "Why aren't you signing?",
    declinePlaceholder: "Tell the sender why",
    declineConfirm: "Decline to sign",
    cancel: "Cancel",
    signedTitle: "Done, you've signed!",
    signedBody: "Once everyone has signed, you'll get the signed PDF and its audit certificate by email.",
    completedBody: "You were the last to sign: the document is complete. We've emailed you the signed PDF.",
    viewVerification: "View verification",
    declinedTitle: "You declined to sign",
    declinedBody: "We've let the sender know.",
    invalidTitle: "This link isn't valid",
    invalidBody:
      "It may be incomplete, or you may have been sent a newer one. Use the link in the latest email.",
    closed: {
      completed: "Everyone has already signed this document.",
      declined: "This document was declined and can no longer be signed.",
      cancelled: "The sender cancelled this request.",
      expired: "The time to sign this document has run out.",
      done: "You've already answered this request. Thank you.",
    },
    errors: {
      link: "This link is no longer valid.",
      closed: "This document can no longer be signed.",
      unverified: "Your verification expired. Confirm your email again.",
      wait: "Wait a minute before asking for another code.",
      limit: "You've asked for too many codes today. Try again tomorrow.",
      email: "We couldn't send the email. Try again in a few minutes.",
      wrong: "That code isn't right.",
      expired: "The code expired. Ask for a new one.",
      locked: "Too many attempts. Ask for a new code.",
      image: "Draw or type your signature first.",
      consent: "Tick the box to agree to signing electronically.",
      reason: "Write the reason.",
      server: "Something went wrong on our side. Please try again.",
    } satisfies Record<SignerError, string>,
    loadError: "I couldn't show the document. Download it to review it.",
  },
} satisfies Record<DocLang, Record<string, unknown>>;

export type SignCopy = (typeof SIGN_COPY)[DocLang];
